name: Build

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository'
        required: true
        type: string
      branch:
        description: 'Branch'
        required: true
        type: string

jobs:
  release:
    name: Release plugin
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win32
            arch: x64
            npm_config_arch: x64
#          - os: windows-latest
#            platform: win32
#            arch: ia32
#            npm_config_arch: ia32
#          - os: windows-latest
#            platform: win32
#            arch: arm64
#            npm_config_arch: arm
          - os: ubuntu-latest
            platform: linux
            arch: x64
            npm_config_arch: x64
#          - os: ubuntu-latest
#            platform: linux
#            arch: arm64
#            npm_config_arch: arm64
#          - os: ubuntu-latest
#            platform: linux
#            arch: armhf
#            npm_config_arch: arm
#          - os: ubuntu-latest
#            platform: alpine
#            arch: x64
#            npm_config_arch: x64
          - os: macos-latest
            platform: darwin
            arch: x64
            npm_config_arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
            npm_config_arch: arm64
        runs-on: ${{ matrix.os }}
        node-version: [ 16.x ]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.branch }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install node modules - Arch: ${{ matrix.arch }} Platform: ${{ matrix.platform }}"
        run: npm ci --target_arch=${{ matrix.arch }} --target_platform=${{ matrix.platform }}
        env:
          npm_config_arch: ${{ matrix.npm_config_arch }}

      - name: Package plugin
        run: npm run package

      - name: Generate package folder name
        id: package-name
        run: echo "PACKAGE_NAME=MariaDB-${{ github.run_id }}-${{ matrix.platform }}-${{ matrix.arch }}" >> $GITHUB_OUTPUT

      - name: Rename package folder
        run: mv release ${{ steps.package-name.outputs.PACKAGE_NAME }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.package-name.outputs.PACKAGE_NAME }}
          path: |
            ${{ steps.package-name.outputs.PACKAGE_NAME }}
