name: Build

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository'
        required: true
        type: string
      branch:
        description: 'Branch'
        required: true
        type: string

jobs:
  build:
    name: Build plugin
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [ 16.x ]
        include:
          - os: windows-latest
            platform: win32
            arch: x64
            npm_config_arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: x64
            npm_config_arch: x64
          - os: macos-latest
            platform: darwin
            arch: x64
            npm_config_arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
            npm_config_arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.branch }}

      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.platform }}-${{ matrix.arch }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node modules
        run: npm ci --target_arch=${{ matrix.arch }} --target_platform=${{ matrix.platform }}
        env:
          npm_config_arch: ${{ matrix.npm_config_arch }}

      - name: Generate package folder name
        id: package-name
        run: echo "PACKAGE_NAME=MariaDB-${{ github.run_id }}-${{ matrix.platform }}-${{ matrix.arch }}" >> $GITHUB_OUTPUT

      - name: Package plugin
        run: npm run package -- --output=${{ steps.package-name.outputs.PACKAGE_NAME }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.package-name.outputs.PACKAGE_NAME }}
          path: ${{ steps.package-name.outputs.PACKAGE_NAME }}
